/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Lab3_gDocs_21024191_TorresAceituno;
// IMPORTS
import java.util.ArrayList;
import java.time.*;
import paradigmaDocs.*;
import documento.*;
import usuario.*;


public class App {
    public static void main(String[] args) {
        ParadigmaDocs plataforma1 = new ParadigmaDocs("GOOGLE DOCS");
        plataforma1.register("Hola", "XD");
        plataforma1.register("XD", "HOLA");
        plataforma1.login("XD", "HOLA");
        System.out.println(plataforma1);
    }
}